[2022-03-27 08:34:31,007] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: airflow_dag.ingest_drivers_task manual__2022-03-27T08:34:27.106151+00:00 [queued]>
[2022-03-27 08:34:31,090] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: airflow_dag.ingest_drivers_task manual__2022-03-27T08:34:27.106151+00:00 [queued]>
[2022-03-27 08:34:31,096] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 08:34:31,099] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-27 08:34:31,103] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 08:34:31,134] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): ingest_drivers_task> on 2022-03-27 08:34:27.106151+00:00
[2022-03-27 08:34:31,150] {standard_task_runner.py:52} INFO - Started process 67 to run task
[2022-03-27 08:34:31,177] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '***_dag', 'ingest_drivers_task', 'manual__2022-03-27T08:34:27.106151+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpokqxwvrc', '--error-file', '/tmp/tmpzd6npkks']
[2022-03-27 08:34:31,182] {standard_task_runner.py:77} INFO - Job 128: Subtask ingest_drivers_task
[2022-03-27 08:34:31,301] {logging_mixin.py:109} INFO - Running <TaskInstance: ***_dag.ingest_drivers_task manual__2022-03-27T08:34:27.106151+00:00 [running]> on host 5159563b36f9
[2022-03-27 08:34:31,386] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sourav Saha
AIRFLOW_CTX_DAG_ID=***_dag
AIRFLOW_CTX_TASK_ID=ingest_drivers_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T08:34:27.106151+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T08:34:27.106151+00:00
[2022-03-27 08:34:31,388] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-27 08:34:31,390] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/ingest_drivers.py']
[2022-03-27 08:34:31,406] {subprocess.py:85} INFO - Output:
[2022-03-27 08:34:35,998] {subprocess.py:89} INFO - [Errno 2] No such file or directory: '/opt/***/f1_csv_files/drivers.csv'
[2022-03-27 08:34:36,510] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-27 08:34:36,571] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=***_dag, task_id=ingest_drivers_task, execution_date=20220327T083427, start_date=20220327T083431, end_date=20220327T083436
[2022-03-27 08:34:36,675] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-27 08:34:36,739] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
