[2022-03-27 04:57:57,848] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: airflow_dag.ingest_drivers_task manual__2022-03-27T04:57:55.345548+00:00 [queued]>
[2022-03-27 04:57:57,924] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: airflow_dag.ingest_drivers_task manual__2022-03-27T04:57:55.345548+00:00 [queued]>
[2022-03-27 04:57:57,927] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 04:57:57,929] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-27 04:57:57,931] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 04:57:57,969] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): ingest_drivers_task> on 2022-03-27 04:57:55.345548+00:00
[2022-03-27 04:57:57,986] {standard_task_runner.py:52} INFO - Started process 116 to run task
[2022-03-27 04:57:58,002] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '***_dag', 'ingest_drivers_task', 'manual__2022-03-27T04:57:55.345548+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpijhct76y', '--error-file', '/tmp/tmpvg8n8b1b']
[2022-03-27 04:57:58,005] {standard_task_runner.py:77} INFO - Job 86: Subtask ingest_drivers_task
[2022-03-27 04:57:58,446] {logging_mixin.py:109} INFO - Running <TaskInstance: ***_dag.ingest_drivers_task manual__2022-03-27T04:57:55.345548+00:00 [running]> on host d05ac524649c
[2022-03-27 04:57:58,846] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sourav Saha
AIRFLOW_CTX_DAG_ID=***_dag
AIRFLOW_CTX_TASK_ID=ingest_drivers_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T04:57:55.345548+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T04:57:55.345548+00:00
[2022-03-27 04:57:58,868] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-27 04:57:58,891] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ingest_drivers.py']
[2022-03-27 04:57:59,215] {subprocess.py:85} INFO - Output:
[2022-03-27 04:58:00,028] {subprocess.py:89} INFO - python: can't open file 'ingest_drivers.py': [Errno 2] No such file or directory
[2022-03-27 04:58:00,064] {subprocess.py:93} INFO - Command exited with return code 2
[2022-03-27 04:58:00,304] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-03-27 04:58:00,386] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=***_dag, task_id=ingest_drivers_task, execution_date=20220327T045755, start_date=20220327T045757, end_date=20220327T045800
[2022-03-27 04:58:00,512] {standard_task_runner.py:92} ERROR - Failed to execute job 86 for task ingest_drivers_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-03-27 04:58:00,600] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-27 04:58:00,728] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
